"""add_production_grade_tables

Revision ID: 90436800dbc5
Revises: 591b58d5d49c
Create Date: 2025-12-30 22:15:05.142430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90436800dbc5'
down_revision: Union[str, Sequence[str], None] = '591b58d5d49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    
    # Create job_descriptions first without the circular foreign key
    op.create_table('job_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_descriptions_id'), 'job_descriptions', ['id'], unique=False)
    op.create_index(op.f('ix_job_descriptions_title'), 'job_descriptions', ['title'], unique=False)
    
    # Now create jd_versions with foreign key to job_descriptions
    op.create_table('jd_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jd_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jd_versions_id'), 'jd_versions', ['id'], unique=False)
    op.create_index(op.f('ix_jd_versions_is_active'), 'jd_versions', ['is_active'], unique=False)
    op.create_index(op.f('ix_jd_versions_jd_id'), 'jd_versions', ['jd_id'], unique=False)
    
    # Now add the foreign key constraint for current_version_id
    op.create_foreign_key('fk_job_descriptions_current_version_id', 'job_descriptions', 'jd_versions', ['current_version_id'], ['id'])
    op.create_table('admin_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jd_id', sa.Integer(), nullable=True),
    sa.Column('setting_name', sa.String(), nullable=False),
    sa.Column('setting_value', sa.JSON(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_settings_id'), 'admin_settings', ['id'], unique=False)
    op.create_index(op.f('ix_admin_settings_jd_id'), 'admin_settings', ['jd_id'], unique=False)
    op.create_index(op.f('ix_admin_settings_setting_name'), 'admin_settings', ['setting_name'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_admin_id'), 'audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=False)
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_index(op.f('ix_candidates_user_id'), 'candidates', ['user_id'], unique=False)
    op.create_table('memory_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('embeddings', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_store_candidate_id'), 'memory_store', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_memory_store_id'), 'memory_store', ['id'], unique=False)
    op.create_index(op.f('ix_memory_store_memory_type'), 'memory_store', ['memory_type'], unique=False)
    op.create_index(op.f('ix_memory_store_session_id'), 'memory_store', ['session_id'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_version', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_provider', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordings_candidate_id'), 'recordings', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_recordings_id'), 'recordings', ['id'], unique=False)
    op.create_index(op.f('ix_recordings_session_id'), 'recordings', ['session_id'], unique=True)
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_version', sa.Integer(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_candidate_id'), 'resumes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.create_table('match_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('jd_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('hard_filter_passed', sa.Boolean(), nullable=False),
    sa.Column('hard_filter_reasons', sa.JSON(), nullable=True),
    sa.Column('weighted_score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('evidence_map', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('threshold_passed', sa.Boolean(), nullable=False),
    sa.Column('settings_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['recordings.session_id'], ),
    sa.ForeignKeyConstraint(['settings_version_id'], ['admin_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_results_candidate_id'), 'match_results', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_match_results_id'), 'match_results', ['id'], unique=False)
    op.create_index(op.f('ix_match_results_jd_id'), 'match_results', ['jd_id'], unique=False)
    op.create_index(op.f('ix_match_results_session_id'), 'match_results', ['session_id'], unique=False)
    op.create_index(op.f('ix_match_results_threshold_passed'), 'match_results', ['threshold_passed'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.Column('transcript_json', sa.JSON(), nullable=False),
    sa.Column('diarization_data', sa.JSON(), nullable=True),
    sa.Column('confidence_scores', sa.JSON(), nullable=True),
    sa.Column('segments', sa.JSON(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_id'), 'transcripts', ['id'], unique=False)
    op.create_index(op.f('ix_transcripts_recording_id'), 'transcripts', ['recording_id'], unique=True)
    op.create_table('evidence_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_result_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('source_location', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_result_id'], ['match_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_tracking_id'), 'evidence_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_tracking_match_result_id'), 'evidence_tracking', ['match_result_id'], unique=False)
    op.create_index(op.f('ix_evidence_tracking_skill_name'), 'evidence_tracking', ['skill_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_tracking_skill_name'), table_name='evidence_tracking')
    op.drop_index(op.f('ix_evidence_tracking_match_result_id'), table_name='evidence_tracking')
    op.drop_index(op.f('ix_evidence_tracking_id'), table_name='evidence_tracking')
    op.drop_table('evidence_tracking')
    op.drop_index(op.f('ix_transcripts_recording_id'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_match_results_threshold_passed'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_session_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_jd_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_candidate_id'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_candidate_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_recordings_session_id'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_id'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_candidate_id'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_memory_store_session_id'), table_name='memory_store')
    op.drop_index(op.f('ix_memory_store_memory_type'), table_name='memory_store')
    op.drop_index(op.f('ix_memory_store_id'), table_name='memory_store')
    op.drop_index(op.f('ix_memory_store_candidate_id'), table_name='memory_store')
    op.drop_table('memory_store')
    op.drop_index(op.f('ix_candidates_user_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_admin_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admin_settings_setting_name'), table_name='admin_settings')
    op.drop_index(op.f('ix_admin_settings_jd_id'), table_name='admin_settings')
    op.drop_index(op.f('ix_admin_settings_id'), table_name='admin_settings')
    op.drop_table('admin_settings')
    op.drop_index(op.f('ix_job_descriptions_title'), table_name='job_descriptions')
    op.drop_index(op.f('ix_job_descriptions_id'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    op.drop_index(op.f('ix_jd_versions_jd_id'), table_name='jd_versions')
    op.drop_index(op.f('ix_jd_versions_is_active'), table_name='jd_versions')
    op.drop_index(op.f('ix_jd_versions_id'), table_name='jd_versions')
    op.drop_table('jd_versions')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
