"""add_transcript_field_to_interview_results

Revision ID: faa57ff9bf5a
Revises: 10a48852813e
Create Date: 2025-08-05 01:02:38.701060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa57ff9bf5a'
down_revision: Union[str, Sequence[str], None] = '10a48852813e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
